cmake_minimum_required(VERSION 3.31)
include_guard(GLOBAL)
message("Actual *.cmake: ${CMAKE_CURRENT_LIST_FILE}")
################################################################################
# Options
# Modules
# Tests
option(BINTJEKIT_BUILD_TESTS "Compile tests" ON)
option(BINTJEKIT_BUILD_TESTS_TIME "Compile time tests" ON)
option(BINTJEKIT_BUILD_TESTS_CONFIGURATION "Compile configuration tests" ON)
if (NOT BINTJEKIT_BUILD_TESTS)
    option(BINTJEKIT_BUILD_TESTS_TIME "Forced OFF : Compile time tests" OFF)
    option(BINTJEKIT_BUILD_TESTS_CONFIGURATION "Forced OFF : Compile configuration tests" OFF)
endif()
# Examples
option(BINTJEKIT_BUILD_EXAMPLES "Compile examples" ON)
option(BINTJEKIT_BUILD_EXAMPLE_MINIMAL "Compile minimal example" ON)
option(BINTJEKIT_BUILD_EXAMPLE_USER "Compile user_classes example" ON)
option(BINTJEKIT_BUILD_EXAMPLE_GOL "Compile gol example" ON)
option(BINTJEKIT_BUILD_EXAMPLE_LIFE "Compile life example" ON)
if (NOT BINTJEKIT_BUILD_EXAMPLES)
    set(BINTJEKIT_BUILD_EXAMPLE_MINIMAL "Forced OFF - Compile minimal example" OFF)
    set(BINTJEKIT_BUILD_EXAMPLE_USER "Forced OFF - Compile user_classes example" OFF)
    set(BINTJEKIT_BUILD_EXAMPLE_GOL "Forced OFF - Compile gol example" OFF)
    set(BINTJEKIT_BUILD_EXAMPLE_LIFE "Forced OFF - Compile life example" OFF)
endif ()
# Benchmarks
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    option(BINTJEKIT_BUILD_BENCHMARKS "Compile benchmarks (Forced OFF in Debug)" OFF)
else()
    option(BINTJEKIT_BUILD_BENCHMARKS "Compile benchmarks" ON)
endif()
option(BINTJEKIT_BUILD_BENCHMARK_TIME "Compile benchmarks test" ON)
if (NOT BINTJEKIT_BUILD_BENCHMARKS)
    option(BINTJEKIT_BUILD_BENCHMARK_TIME "Forced OFF : Compile benchmark test" OFF)
endif()
if (CMAKE_BUILD_TYPE STREQUAL "Debug" AND BINTJEKIT_BUILD_BENCHMARKS)
    message(STATUS "Les benchmarks sont désactivés en mode Debug pour des résultats pertinents.")
endif()
if (BINTJEKIT_BUILD_BENCHMARKS)
    # Ici votre configuration des benchmarks avec nanobench
    if (NOT CMAKE_BUILD_TYPE STREQUAL "Release")
        message(WARNING "Les benchmarks devraient être compilés en Release pour des résultats optimaux !")
    endif()
endif()
